// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  calendar: dynamic(() => import("./Calendar")),
  card_grid: dynamic(() => import("./CardGrid")),
  contact_card: dynamic(() => import("./ContactCard")),
  hero: dynamic(() => import("./Hero")),
  image_gallery: dynamic(() => import("./ImageGallery")),
  navbar: dynamic(() => import("./Navbar")),
  spacer: dynamic(() => import("./Spacer")),
  table: dynamic(() => import("./Table")),
};
